---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
  run_list: ["recipe[apt]"]

suites:
- name: default
  run_list: ["recipe[mysql::server]", "recipe[app_database_test]"]
  attributes:
    mysql:
      server_root_password: vagrant
      server_repl_password: vagrant
      server_debian_password: vagrant
